steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$BRANCH_NAME:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$BRANCH_NAME:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', '$PROJECT_ID', '--image', 'gcr.io/$PROJECT_ID/$BRANCH_NAME:latest', '--platform', 'managed', '--region', 'us-central1']
images: ['gcr.io/$PROJECT_ID/$BRANCH_NAME:latest']